<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class Classes extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert multiple class records
        DB::table('classes')->insert([
            // //first year, first sem
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0102',
            //     'section' => 2,
            //     'name' => 'Discrete Structures 1',
            //     'units' => 3,
            //     'day' => 'Monday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0101',
            //     'section' => 2,
            //     'name' => 'Introduction to Computing (Lecture)',
            //     'units' => 2,
            //     'day' => 'Tuesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0101.1',
            //     'section' => 2,
            //     'name' => 'Introduction to Computing (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Tuesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0102',
            //     'section' => 2,
            //     'name' => 'Fundamentals of Programming (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 310',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0102.1',
            //     'section' => 2,
            //     'name' => 'Fundamentals of Programming (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'IPP 0010-31',
            //     'section' => 1,
            //     'name' => 'Interdisiplinaryong Pagbasa at Pagsulat Tungo Sa Mabisang Pagpapahayag',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'MMW 0001-15',
            //     'section' => 1,
            //     'name' => 'Mathematics in the Modern World',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'NSTP 01-16',
            //     'section' => 1,
            //     'name' => 'National Service Training Program 1 ( Cwts/rotc)',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'PCM 0006-45',
            //     'section' => 1,
            //     'name' => 'Purposive Communication',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'PED 0001-77',
            //     'section' => 1,
            //     'name' => 'Foundation of Physical Activities',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'STS 0002-29',
            //     'section' => 1,
            //     'name' => 'Science, Technology and Society',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // //first year, second sem
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0211',
            //     'section' => 1,
            //     'name' => 'Discrete Structures 2',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0223',
            //     'section' => 1,
            //     'name' => 'Human Computer Interaction',
            //     'units' => 3,
            //     'day' => 'Friday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0103',
            //     'section' => 1,
            //     'name' => 'Intermediate Programming (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0103.1',
            //     'section' => 1,
            //     'name' => 'Intermediate Programming (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0104',
            //     'section' => 1,
            //     'name' => 'Data Structures and Algorithms (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0104.1',
            //     'section' => 1,
            //     'name' => 'Data Structures and Algorithms (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'LWR 0009-19',
            //     'section' => 1,
            //     'name' => 'Life and Works of Rizal',
            //     'units' => 3,
            //     'day' => 'Tuesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'NSTP 02-16',
            //     'section' => 1,
            //     'name' => 'National Service Training Program 2 ( Cwts/rotc)',
            //     'units' => 3,
            //     'day' => 'Thursday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'PED 0012-61',
            //     'section' => 1,
            //     'name' => 'Group Exercise',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'RPH 0004-20',
            //     'section' => 1,
            //     'name' => 'Readings in Philippine History',
            //     'units' => 3,
            //     'day' => 'Monday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'TCW 0005-15',
            //     'section' => 1,
            //     'name' => 'The Contemporary World',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // //second year, first sem
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0212',
            //     'section' => 1,
            //     'name' => 'Object Oriented Programming (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0212.1',
            //     'section' => 1,
            //     'name' => 'Object Oriented Programming (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Tuesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0213',
            //     'section' => 1,
            //     'name' => 'Logic Design and Digital Computer Circuits (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0213.1',
            //     'section' => 1,
            //     'name' => 'Logic Design and Digital Computer Circuits (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0224',
            //     'section' => 1,
            //     'name' => 'Operation Research',
            //     'units' => 3,
            //     'day' => 'Friday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ETH 0008-29',
            //     'section' => 1,
            //     'name' => 'Ethics',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0105',
            //     'section' => 1,
            //     'name' => 'Information Management (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ICC 0105.1',
            //     'section' => 1,
            //     'name' => 'Information Management (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'ITE 0001',
            //     'section' => 1,
            //     'name' => 'Living in the it Era',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'PED 0033-12',
            //     'section' => 1,
            //     'name' => 'Arnis',
            //     'units' => 2,
            //     'day' => 'Tuesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'UTS 0003-16',
            //     'section' => 1,
            //     'name' => 'Understanding the Self',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // //second year, second sem
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'AAP 0007-40',
            //     'section' => 1,
            //     'name' => 'Art Appreciation',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CBM 0016-14',
            //     'section' => 1,
            //     'name' => 'The Entrepreneurial Mind',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0221',
            //     'section' => 1,
            //     'name' => 'Algorithm and Complexity',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'student_id' => 1,
            //     'professor_id' => 1,
            //     'code' => 'CSC 0222',
            //     'section' => 1,
            //     'name' => 'Architecture and Organization (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'CSC 0222.1',
            //     'section' => 1,
            //     'name' => 'Architecture and Organization (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Monday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'CSC 0316',
            //     'section' => 1,
            //     'name' => 'Information Assurance Security',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'GES 0013',
            //     'section' => 1,
            //     'name' => 'Environmental Science',
            //     'units' => 3,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'ICC 0106',
            //     'section' => 1,
            //     'name' => 'Applications Development and Emerging Technologies (Lecture)',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'ICC 0106.1',
            //     'section' => 1,
            //     'name' => 'Applications Development and Emerging Technologies (Laboratory)',
            //     'units' => 1,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Gusaling Villegas',
            //     'room' => 'GV 311',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'professor_id' => 1,
            //     'code' => 'PED 0054-3',
            //     'section' => 1,
            //     'name' => 'Soccer',
            //     'units' => 2,
            //     'day' => 'Wednesday',
            //     'start_time' => '09:00:00',
            //     'end_time' => '12:00:00',
            //     'building' => 'Field',
            //     'room' => 'Field',
            //     'type' => 'face-to-face',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

// ----------------------------------------------
            //third year, first sem
            [
                'student_record_id' => 5,
                'professor_id' => 202101353,
                'code' => 'CSC 0314',
                'section' => 2,
                'name' => 'Operating System (Lec)',
                'units' => 2,
                'day' => 'Thursday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In the lecture component of Operating System class, students study the design, implementation, and operation of modern operating systems. Topics include process management, memory management, file systems, device management, and security. Students learn about the key components of an operating system, their interactions, and how they enable efficient and reliable execution of software applications.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101353,
                'code' => 'CSC 0314.1',
                'section' => 2,
                'name' => 'Operating System (Lab)',
                'units' => 1,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 311',
                'type' => 'face-to-face',
                'description' => 'In the Operating System (Lab) class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101352,
                'code' => 'CSC 0315',
                'section' => 2,
                'name' => 'Intelligent System (Lec)',
                'units' => 2,
                'day' => 'Wednesday',
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'The Intelligent Systems class lecture component gives an in-depth look at the principles, techniques, and applications of AI and machine learning. Topics covered could include search algorithms, knowledge representation, reasoning, planning, probabilistic models, neural networks, deep learning, and natural language processing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101352,
                'code' => 'CSC 0315.1',
                'section' => 2,
                'name' => 'Intelligent System (Lab)',
                'units' => 1,
                'day' => 'Monday',
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'The Intelligent Systems laboratory class teaches students about machine learning, pattern recognition, data mining, and computational intelligence through hands-on activities. Students construct and evaluate intelligent systems using programming languages such as Python, as well as popular libraries and frameworks such as TensorFlow, scikit-learn, and PyTorch.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101354,
                'code' => 'CSC 0311',
                'section' => 2,
                'name' => 'Automata Theory and Formal Languages',
                'units' => 3,
                'day' => 'Tuesday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'This class teaches the theoretical foundations of computer science, focusing on formal models of computation and their applications. Students learn to analyze and design algorithms for various computational problems using formal language theory. ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101351,
                'code' => 'CSC 0312',
                'section' => 2,
                'name' => 'Programming Languages (Lec)',
                'units' => 2,
                'day' => 'Friday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'This class introduces students to the fundamental concepts and principles underlying various programming languages. Topics covered include syntax, semantics, data types, control structures, functions, and object-oriented programming.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101351,
                'code' => 'CSC 0312.1',
                'section' => 2,
                'name' => 'Programming Languages (Lab)',
                'units' => 1,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 3',
                'type' => 'face-to-face',
                'description' => 'This class offers practical sessions to reinforce the concepts learned in lectures. Students get hands-on experience with different programming paradigms, language features, and implementation techniques. Lab assignments often involve writing code to solve problems, understanding language semantics, and exploring language-specific libraries and tools.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101350,
                'code' => 'CSC 0313',
                'section' => 2,
                'name' => 'Software Engineering (Lec)',
                'units' => 2,
                'day' => 'Thursday',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'The lecture component of the Software Engineering class explores the principles, methodologies, and best practices involved in the systematic development of high-quality software systems. Topics include software requirements engineering, software design, software testing, software maintenance, and project management. Students learn about different software development processes such as waterfall, agile, and DevOps, and gain practical insights into software development lifecycle phases.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 5,
                'professor_id' => 202101350,
                'code' => 'CSC 0313.1',
                'section' => 2,
                'name' => 'Software Engineering (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 1',
                'type' => 'face-to-face',
                'description' => 'The laboratory component of the Software Engineering class provides students with practical experience in applying software engineering principles and techniques to real-world software development projects. Students work in groups to go through the entire software development lifecycle, from requirements elicitation to deployment and maintenance. The lab emphasizes collaboration, communication, and problem-solving skills essential for successful software development projects.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

// -----------------------------------------------
            //second year, second sem
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0314.1',
                'section' => 2,
                'name' => 'Badminton',
                'units' => 2,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 311',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0315.1',
                'section' => 2,
                'name' => 'The Entrepreneurial Mind',
                'units' => 3,
                'day' => 'Monday',
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0311',
                'section' => 2,
                'name' => 'Algorithm and Complexity',
                'units' => 3,
                'day' => 'Tuesday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0315',
                'section' => 2,
                'name' => 'Information Assurance Security',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0312.1',
                'section' => 2,
                'name' => 'Environmental Science',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 3',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0314',
                'section' => 2,
                'name' => 'Applications Development and Emerging Technologies (Lec)',
                'units' => 2,
                'day' => 'Thursday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0313',
                'section' => 2,
                'name' => 'Applications Development and Emerging Technologies (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0312',
                'section' => 2,
                'name' => 'Architecture and Organization (Lec)',
                'units' => 2,
                'day' => 'Friday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 4,
                'professor_id' => 202101350,
                'code' => 'CSC 0313.1',
                'section' => 2,
                'name' => 'Architecture and Organization (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 1',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
// -------------------------------------------
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'CSC 0212',
                'section' => 2,
                'name' => 'Object Oriented Programming (Lec)',
                'units' => 2,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 311',
                'type' => 'face-to-face',
                'description' => 'This lecture covers the fundamentals of object-oriented programming, including classes, objects, inheritance, and polymorphism, using Java or a similar language.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'CSC 0212.1',
                'section' => 2,
                'name' => 'Object Oriented Programming (Lab)',
                'units' => 1,
                'day' => 'Monday',
                'start_time' => '10:45:00',
                'end_time' => '12:15:00',
                'building' => 'Computer Lab 2',
                'room' => 'CL 204',
                'type' => 'face-to-face',
                'description' => 'In this lab, students apply the principles of object-oriented programming through hands-on exercises and projects.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'CSC 0213',
                'section' => 2,
                'name' => 'Logic Design and Digital Computer Circuits (Lec)',
                'units' => 2,
                'day' => 'Tuesday',
                'start_time' => '13:00:00',
                'end_time' => '14:30:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 309',
                'type' => 'face-to-face',
                'description' => 'Covers the fundamentals of digital circuits and logic design, including binary systems, Boolean algebra, and logic gates.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'CSC 0213.1',
                'section' => 2,
                'name' => 'Logic Design and Digital Computer Circuits (Lab)',
                'units' => 1,
                'day' => 'Tuesday',
                'start_time' => '14:45:00',
                'end_time' => '16:15:00',
                'building' => 'Engineering Lab',
                'room' => 'EL 201',
                'type' => 'face-to-face',
                'description' => 'This lab complements the lecture by providing practical experience with digital circuits and logic design.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'CSC 0224',
                'section' => 2,
                'name' => 'Operation Research',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '08:00:00',
                'end_time' => '10:30:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 310',
                'type' => 'face-to-face',
                'description' => 'This course introduces the basic concepts of operations research, including linear programming, queuing theory, and the simplex method.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'ICC 0105',
                'section' => 2,
                'name' => 'Information Management (Lec)',
                'units' => 2,
                'day' => 'Wednesday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'building' => 'Info Tech Building',
                'room' => 'IT 202',
                'type' => 'face-to-face',
                'description' => 'Focuses on the principles of managing information systems and technology in organizations, including database management systems.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'ICC 0105.1',
                'section' => 2,
                'name' => 'Information Management (Lab)',
                'units' => 1,
                'day' => 'Wednesday',
                'start_time' => '12:45:00',
                'end_time' => '14:15:00',
                'building' => 'Info Tech Building',
                'room' => 'Lab 203',
                'type' => 'face-to-face',
                'description' => 'Provides hands-on experience with database management systems and other information management tools.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'ITE 0001',
                'section' => 2,
                'name' => 'Living in the IT Era',
                'units' => 3,
                'day' => 'Thursday',
                'start_time' => '09:00:00',
                'end_time' => '11:30:00',
                'building' => 'Info Tech Building',
                'room' => 'IT 204',
                'type' => 'face-to-face',
                'description' => 'An exploration of the impact of information technology on society and individuals’ lives, focusing on ethical, legal, and social issues.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'ETH 0008',
                'section' => 2,
                'name' => 'Ethics',
                'units' => 3,
                'day' => 'Thursday',
                'start_time' => '12:00:00',
                'end_time' => '14:30:00',
                'building' => 'Humanities Building',
                'room' => 'HB 101',
                'type' => 'face-to-face',
                'description' => 'A study of ethical theories and moral issues in contemporary society, emphasizing critical thinking and ethical decision-making.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'UTS 0003',
                'section' => 2,
                'name' => 'Understanding the Self',
                'units' => 3,
                'day' => 'Friday',
                'start_time' => '08:00:00',
                'end_time' => '10:30:00',
                'building' => 'Humanities Building',
                'room' => 'HB 102',
                'type' => 'face-to-face',
                'description' => 'An interdisciplinary course that explores different dimensions of the self from psychological, philosophical, and sociological perspectives.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 3,
                'professor_id' => 202101350,
                'code' => 'PE 13',
                'section' => 2,
                'name' => 'Basketball',
                'units' => 2,  // Note: Units are likely incorrect as negative units don't make sense, assuming typo in the original data and setting to positive.
                'day' => 'Friday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'building' => 'Sports Complex',
                'room' => 'Gym 1',
                'type' => 'face-to-face',
                'description' => 'Practical instruction in badminton techniques and strategies, focusing on skill development and game tactics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
// -----------------------------------------------
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0223',
                'section' => 2,
                'name' => 'Human Computer Interaction',
                'units' => 3,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 311',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0315.1',
                'section' => 2,
                'name' => 'Discrete Structures 2',
                'units' => 3,
                'day' => 'Monday',
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0311',
                'section' => 2,
                'name' => 'The Contemporary World',
                'units' => 3,
                'day' => 'Tuesday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0315',
                'section' => 2,
                'name' => 'Readings in Philippine History',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0312.1',
                'section' => 2,
                'name' => 'Life and Works of Rizal',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 3',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0314',
                'section' => 2,
                'name' => 'Data Structures and Algorithms (Lec)',
                'units' => 2,
                'day' => 'Thursday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0313',
                'section' => 2,
                'name' => 'Data Structures and Algorithms (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0312',
                'section' => 2,
                'name' => 'Intermediate Programming (Lec)',
                'units' => 2,
                'day' => 'Friday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 2,
                'professor_id' => 202101350,
                'code' => 'CSC 0313.1',
                'section' => 2,
                'name' => 'Intermediate Programming (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 1',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // -------------------------------------------

            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0314.1',
                'section' => 2,
                'name' => 'Foundation of Physical Activities',
                'units' => 2,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '12:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'GV 311',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0315.1',
                'section' => 2,
                'name' => 'Science, Technology and Society',
                'units' => 3,
                'day' => 'Monday',
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0311',
                'section' => 2,
                'name' => 'Purposive Communication',
                'units' => 3,
                'day' => 'Tuesday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 4',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0315',
                'section' => 2,
                'name' => 'Mathematics in the Modern World',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0312.1',
                'section' => 2,
                'name' => 'Discrete Structures 1',
                'units' => 3,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '17:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 3',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0314',
                'section' => 2,
                'name' => 'Fundamentals of Programming (Lec)',
                'units' => 2,
                'day' => 'Thursday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0313',
                'section' => 2,
                'name' => 'Fundamentals of Programming (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '16:00:00',
                'end_time' => '18:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0312',
                'section' => 2,
                'name' => 'Introduction to Computing (Lec)',
                'units' => 2,
                'day' => 'Friday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'building' => '',
                'room' => 'MS Teams',
                'type' => 'online',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_record_id' => 1,
                'professor_id' => 202101350,
                'code' => 'CSC 0313.1',
                'section' => 2,
                'name' => 'Introduction to Computing (Lab)',
                'units' => 1,
                'day' => 'Thursday',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'building' => 'Gusaling Villegas',
                'room' => 'Comp. Lab 1',
                'type' => 'face-to-face',
                'description' => 'In this class, students explore key concepts and hands-on applications of operating systems, covering system processes, memory management, and file systems. Through practical exercises, they gain skills to design and optimize OS, preparing for real-world computer science challenges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
