<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'subject_code' => 'CS101',
                'subject_title' => 'Introduction to Computer Science',
                'course_number' => '101',
                'units' => 3,
                'class_code' => 101,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CS102',
                'subject_title' => 'Data Structures',
                'course_number' => '102',
                'units' => 4,
                'class_code' => 102,
                'pre_requisite' => 'CS101',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314',
                'subject_title' => 'Operating System (Lec)',
                'course_number' => '0314',
                'units' => 2,
                'class_code' => 314,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314.1',
                'subject_title' => 'Operating System (Lab)',
                'course_number' => '0314.1',
                'units' => 1,
                'class_code' => 3141,
                'pre_requisite' => 'CSC 0314',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315',
                'subject_title' => 'Intelligent System (Lec)',
                'course_number' => '0315',
                'units' => 2,
                'class_code' => 315,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315.1',
                'subject_title' => 'Intelligent System (Lab)',
                'course_number' => '0315.1',
                'units' => 1,
                'class_code' => 3151,
                'pre_requisite' => 'CSC 0315',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0311',
                'subject_title' => 'Automata Theory and Formal Languages',
                'course_number' => '0311',
                'units' => 3,
                'class_code' => 311,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312',
                'subject_title' => 'Programming Languages (Lec)',
                'course_number' => '0312',
                'units' => 2,
                'class_code' => 312,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312.1',
                'subject_title' => 'Programming Languages (Lab)',
                'course_number' => '0312.1',
                'units' => 1,
                'class_code' => 3121,
                'pre_requisite' => 'CSC 0312',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313',
                'subject_title' => 'Software Engineering (Lec)',
                'course_number' => '0313',
                'units' => 2,
                'class_code' => 313,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313.1',
                'subject_title' => 'Software Engineering (Lab)',
                'course_number' => '0313.1',
                'units' => 1,
                'class_code' => 3131,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0311',
                'subject_title' => 'Algorithm and Complexity',
                'course_number' => '0311',
                'units' => 3,
                'class_code' => 311,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315',
                'subject_title' => 'Information Assurance Security',
                'course_number' => '0315',
                'units' => 3,
                'class_code' => 315,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312.1',
                'subject_title' => 'Environmental Science',
                'course_number' => '0312.1',
                'units' => 3,
                'class_code' => 3121,
                'pre_requisite' => 'CSC 0312',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314',
                'subject_title' => 'Applications Development and Emerging Technologies (Lec)',
                'course_number' => '0314',
                'units' => 2,
                'class_code' => 314,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313',
                'subject_title' => 'Applications Development and Emerging Technologies (Lab)',
                'course_number' => '0313',
                'units' => 1,
                'class_code' => 313,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312',
                'subject_title' => 'Architecture and Organization (Lec)',
                'course_number' => '0312',
                'units' => 2,
                'class_code' => 312,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313.1',
                'subject_title' => 'Architecture and Organization (Lab)',
                'course_number' => '0313.1',
                'units' => 1,
                'class_code' => 3131,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0212',
                'subject_title' => 'Object Oriented Programming (Lec)',
                'course_number' => '0212',
                'units' => 2,
                'class_code' => 212,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0212.1',
                'subject_title' => 'Object Oriented Programming (Lab)',
                'course_number' => '0212.1',
                'units' => 1,
                'class_code' => 2121,
                'pre_requisite' => 'CSC 0212',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0213',
                'subject_title' => 'Logic Design and Digital Computer Circuits (Lec)',
                'course_number' => '0213',
                'units' => 2,
                'class_code' => 213,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0213.1',
                'subject_title' => 'Logic Design and Digital Computer Circuits (Lab)',
                'course_number' => '0213.1',
                'units' => 1,
                'class_code' => 2131,
                'pre_requisite' => 'CSC 0213',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0224',
                'subject_title' => 'Operation Research',
                'course_number' => '0224',
                'units' => 3,
                'class_code' => 224,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'ICC 0105',
                'subject_title' => 'Information Management (Lec)',
                'course_number' => '0105',
                'units' => 2,
                'class_code' => 105,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'ICC 0105.1',
                'subject_title' => 'Information Management (Lab)',
                'course_number' => '0105.1',
                'units' => 1,
                'class_code' => 1051,
                'pre_requisite' => 'ICC 0105',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'ITE 0001',
                'subject_title' => 'Living in the IT Era',
                'course_number' => '0001',
                'units' => 3,
                'class_code' => 1,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'ETH 0008',
                'subject_title' => 'Ethics',
                'course_number' => '0008',
                'units' => 3,
                'class_code' => 8,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'UTS 0003',
                'subject_title' => 'Understanding the Self',
                'course_number' => '0003',
                'units' => 3,
                'class_code' => 3,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'PE 13',
                'subject_title' => 'Basketball',
                'course_number' => '13',
                'units' => 2,
                'class_code' => 13,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0223',
                'subject_title' => 'Human Computer Interaction',
                'course_number' => '0223',
                'units' => 3,
                'class_code' => 223,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315.1',
                'subject_title' => 'Discrete Structures 2',
                'course_number' => '0315.1',
                'units' => 3,
                'class_code' => 3151,
                'pre_requisite' => 'CSC 0315',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0311',
                'subject_title' => 'The Contemporary World',
                'course_number' => '0311',
                'units' => 3,
                'class_code' => 311,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315',
                'subject_title' => 'Readings in Philippine History',
                'course_number' => '0315',
                'units' => 3,
                'class_code' => 315,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312.1',
                'subject_title' => 'Life and Works of Rizal',
                'course_number' => '0312.1',
                'units' => 3,
                'class_code' => 3121,
                'pre_requisite' => 'CSC 0312',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314',
                'subject_title' => 'Data Structures and Algorithms (Lec)',
                'course_number' => '0314',
                'units' => 2,
                'class_code' => 314,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313',
                'subject_title' => 'Data Structures and Algorithms (Lab)',
                'course_number' => '0313',
                'units' => 1,
                'class_code' => 313,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312',
                'subject_title' => 'Intermediate Programming (Lec)',
                'course_number' => '0312',
                'units' => 2,
                'class_code' => 312,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313.1',
                'subject_title' => 'Intermediate Programming (Lab)',
                'course_number' => '0313.1',
                'units' => 1,
                'class_code' => 3131,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312',
                'subject_title' => 'Introduction to Computing (Lec)',
                'course_number' => '0312',
                'units' => 2,
                'class_code' => 312,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313.1',
                'subject_title' => 'Introduction to Computing (Lab)',
                'course_number' => '0313.1',
                'units' => 1,
                'class_code' => 3131,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314.1',
                'subject_title' => 'Foundation of Physical Activities',
                'course_number' => '0314.1',
                'units' => 2,
                'class_code' => 3141,
                'pre_requisite' => 'CSC 0314',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315.1',
                'subject_title' => 'Science, Technology and Society',
                'course_number' => '0315.1',
                'units' => 3,
                'class_code' => 3151,
                'pre_requisite' => 'CSC 0315',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0311',
                'subject_title' => 'Purposive Communication',
                'course_number' => '0311',
                'units' => 3,
                'class_code' => 311,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0315',
                'subject_title' => 'Mathematics in the Modern World',
                'course_number' => '0315',
                'units' => 3,
                'class_code' => 315,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0312.1',
                'subject_title' => 'Discrete Structures 1',
                'course_number' => '0312.1',
                'units' => 3,
                'class_code' => 3121,
                'pre_requisite' => 'CSC 0312',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0314',
                'subject_title' => 'Fundamentals of Programming (Lec)',
                'course_number' => '0314',
                'units' => 2,
                'class_code' => 314,
                'pre_requisite' => '',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'subject_code' => 'CSC 0313',
                'subject_title' => 'Fundamentals of Programming (Lab)',
                'course_number' => '0313',
                'units' => 1,
                'class_code' => 313,
                'pre_requisite' => 'CSC 0313',
                'program_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
